describe("test harness", function()
  it("loads all surviving zxz modules from runtimepath", function()
    assert.is_truthy(require("zxz"))
    assert.is_truthy(require("zxz.complete"))
    assert.is_truthy(require("zxz.complete.ghost"))
    assert.is_truthy(require("zxz.complete.cache"))
    assert.is_truthy(require("zxz.complete.context"))
    assert.is_truthy(require("zxz.complete.debounce"))
    assert.is_truthy(require("zxz.core.config"))
    assert.is_truthy(require("zxz.core.acp_client"))
    assert.is_truthy(require("zxz.core.acp_transport"))
    assert.is_truthy(require("zxz.core.log"))
    assert.is_truthy(require("zxz.core.paths"))
  end)
end)
