describe("test harness", function()
	it("loads all surviving zxz modules from runtimepath", function()
		assert.are.equal(require("zxz"), require("0x0"))
		assert.is_truthy(require("zxz"))
		assert.is_truthy(require("zxz.complete"))
		assert.is_truthy(require("zxz.complete.ghost"))
		assert.is_truthy(require("zxz.complete.cache"))
		assert.is_truthy(require("zxz.complete.context"))
		assert.is_truthy(require("zxz.complete.debounce"))
		assert.is_truthy(require("zxz.core.config"))
		assert.is_truthy(require("zxz.core.completion_client"))
		assert.is_truthy(require("zxz.core.completion_transport"))
		assert.is_truthy(require("zxz.core.gateway_auth"))
		assert.is_truthy(require("zxz.core.model_catalog"))
		assert.is_truthy(require("zxz.core.log"))
		assert.is_truthy(require("zxz.core.paths"))
	end)
end)
